### PR TITLE
Multiple fixes

### PR DESCRIPTION
**Pull request by marcelgerber**
I'm working on multiple improvements right now.

### CODE REVIEW

**Comment by zaggino** [comment]
Ok cool, I'm currently working solely on socket server for domains so there shouldn't be conflicts.

**Comment by marcelgerber** [comment]
Extra note for 8a29b38 and 48ce44c:
As a side effect, it also changes the User Agent string to be correct: `Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Brackets-Electron-dev/1.3.0-0 Chrome/42.0.2311.107 Electron/0.25.2 Safari/537.36`

(Brackets currently has `Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Brackets/1.3.0.0 Chrome/39.0.2171.36 Safari/537.36`, so they are very similar)

**Comment by marcelgerber** [comment]
Ready to merge.

**Comment by zaggino** [comment]
:+1: good work!

**Pull request merged**
