### PR TITLE
Add support for showOpenDialog/showSaveDialog

### PR DESCRIPTION
**Pull request by marcelgerber**
Seems to work (although `openSaveDialog`'s `proposedNewFilename` doesn't work yet). Not perfect, though.

### CODE REVIEW

**Comment by marcelgerber** [comment]
I wonder if we should make `fixPath` an exported function somewhere (even though it's not a difficult one).

**Comment by zaggino** [comment]
yeah, lets have some utils.js file in the /app folder

**Comment by zaggino** [comment]
probably rename it to fixWindowsSlashes or something

**Comment by zaggino** [comment]
this is the correct name - https://github.com/zaggino/brackets-electron/blob/master/src/file/FileUtils.js#L253-L258 :)

**Pull request merged**
