### PR TITLE
Update dev dependencies

### PR DESCRIPTION
**Pull request by ingorichter**
the weekly update of dev dependencies

### CODE REVIEW

**Comment by nethip** [comment]
@ingorichter I ran to this strange dependency error with `is-property` library not being present, which is required by `electron-prebuilt`. I then went ahead and added `is-property` as one of the dependencies and the build succeeded fine. Should we add `is-property` as one of the dependencies?

**Comment by ingorichter** [comment]
@nethip I haven't seen the issue yet. The lib isn't mentioned in `package.json` of `electron-prebuilt`.

**Comment by nethip** [comment]
@ingorichter hmm.. That's strange. On my system `npm install` fails just for this reason.

**Comment by marcelgerber** [comment]
It works for me, too.
Thus merging.

@nethip You could try to delete your entire `node_modules` folder and do a fresh `npm install` thereafter. That sometimes resolves such npm issues.

**Pull request merged**
