### PR TITLE
get this up to date

### PR DESCRIPTION
**Pull request by zaggino**

### CODE REVIEW

**Comment by ingorichter** [comment]
Conflicts... sigh

**Comment by zaggino** [comment]
Merged, I will get this running on latest electron soon.

**Comment by MiguelCastillo** [comment]
Awesome! One step at a time

**Comment by mackenza** [comment]
is this still a thing?

I have to admit, I am no longer using Brackets but would still be interested in seeing it work on Electron.

Question for you guys who know the internals of Brackets (I am looking at you @zaggino @ingorichter @MiguelCastillo ), if it moved to Electron, would the whole way that Brackets uses Node in the client/server way with contexts be unnecessary? One of the best parts of Electron is using Node natively in any js file, whether it's a Renderer or not.

**Comment by zaggino** [comment]
@mackenza We've decided to brush of some dust from this and hopefully get a stable working electron build. To that second thing, yes you're right - client/server node way would be unnecessary. Although it could be used to spawn processes for domains taking advantage of cpu cores and preventing domain conflicts.

**Comment by mackenza** [comment]
@zaggino thanks for the info.

I think an Electron version would get my interest in Brackets going again. I still can't really love Atom... but VSCode is pretty damn good especially for Node dev.

It makes you wonder what the possibilities could be for Brackets... ;)

**Comment by ingorichter** [comment]
@mackenza I'm getting excited, thinking about getting rid of CEF in Brackets. It causes a ton of issues across platforms and updating is a painful and long process. Regressions are not always easy to detect and sometimes getting a new version to compile is a bunch of work.
As @zaggino already mentioned, we don't have to deal with an external node process anymore. If there are any extensions that require to spawn an external process, they could happily do it and we wouldn't care about it (proper error handling implemented). A Brackets version based on Electron would be so much more powerful and easier to maintain. We could focus more on features and move the needle towards having more powerful web design and prototyping features. And we could probably resolve some annoying limitations (file indexing) by using a different foundation. Just my two cents. I'm still excited about transitioning away from CEF. I don't know yet what the impact would be for Intel XDK (@busykai could shed some light on it), or how this transition would impact the integration work of Brackets into the next version of Dreamweaver. There is a huge potential to make some big changes for the better. Let's get it started. :-)

**Pull request merged**
