### PR TITLE
Remember window position

### PR DESCRIPTION
**Pull request by marcelgerber**
This is an early implementation and I'd like to get feedback on the approach.

I'd like to use the `shell-config.json` file for [other options](https://github.com/atom/electron/blob/master/docs/api/browser-window.md#new-browserwindowoptions), too.

### CODE REVIEW

**Comment by zaggino** [comment]
hello slack

**Comment by zaggino** [comment]
nicely done :+1:

**Comment by marcelgerber** [comment]
Note: Restore window is not yet implemented.
Could you maybe add a TODO comment so we don't forget about it?

**Comment by zaggino** [comment]
Sure

**Comment by zaggino** [comment]
Altough it's kind of hard to miss even without the comment :D

**Pull request merged**
